apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: smoke-tests-
  annotations:
    argocd.argoproj.io/sync-wave: "10"   
  labels:
    codefresh.io/cert: smoke-job  
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
